import type { Metadata } from "next";
import "./globals.css";
import Cart from "./Components/cart/Cart";
import Navbar from "./Components/Navbar";
import ToasterProvider from "./Others/providers/ToasterProvider";
import WishlistModal from "./Components/modal/WishListModal";
import AddToWishlistModal from "./Components/modal/AddToWishlistModal";
import Loader from "./Components/Loader";
import Footer from "./Components/Footer";

export const metadata: Metadata = {
  title: "Best Buy",
  manifest: "/manifest.json",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang="en">
      <body>
        <ToasterProvider />
        <Loader />
        <div>
          <AddToWishlistModal />
          <WishlistModal />
          <Cart />
          <Navbar />
          <div className="py-32">{children}</div>
          <Footer/>
        
        </div>
      </body>
    </html>
  );
}
