import type { Metadata } from "next";
import "./globals.css";
import Cart from "./Components/cart/Cart";
import Navbar from "./Components/Navbar";
import ToasterProvider from "./Others/providers/ToasterProvider";
import WishlistModal from "./Components/modal/WishListModal";
import AddToWishlistModal from "./Components/modal/AddToWishlistModal";
import Loader from "./Components/Loader";
import Footer from "./Components/Footer";
import BackButton from "./Components/BackButton";
import {Poppins} from "next/font/google"
export const metadata: Metadata = {
  title: "Best Buy",
  manifest: "/manifest.json",
  description: "Generated by create next app",
  
};
const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body>
        <ToasterProvider />
        <Loader />
        <div>
          <AddToWishlistModal />
          <WishlistModal />
          <Cart />
          <Navbar />
          
          <div className="py-32 sm:py-28 p-2 sm:p-0 h-[60vh] mb-20">
            <>
            <BackButton/>
            {children}
            </>
          </div>
        </div>
     

      </body>
    </html>
  );
}
